server {
    listen 80;
    server_name your_domain_or_ip; # Substitua pelo seu domínio ou IP do VPS

    location / {
        proxy_pass http://localhost:3000; # A porta que sua aplicação Node.js está rodando (PM2)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection \'upgrade\';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Configuração para Socket.IO
    location /socket.io/ {
        proxy_pass http://localhost:3000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection \'upgrade\';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400s; # Tempo limite para conexões WebSocket
    }
}


